[package]
name = "pnl-fetcher"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "3"
tokio = "1.49.0"
transaction-cache = { path = "../transaction-cache" }
utils = { path = "../utils" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.29"
dotenvy = "0.15.7"
